# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RunHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_name', models.CharField(max_length=50)),
                ('run_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RunValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_dt', models.DateTimeField()),
                ('value_val', models.FloatField()),
                ('run_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selbox.RunHistory')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='runvalues',
            unique_together=set([('run_history', 'value_dt')]),
        ),
    ]
